[package]
name = "dragoman"
version = "0.1.0"
authors = ["Sacha <sacha.arbonel@hotmail.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustpython-parser = "0.1.2"
lazy_static = "1.4.0"
